In [22]:
import numpy as np
import pandas as pd
from Classes.PercepTeacher import PerceptronTeacher
from Functions.function_of_activation import sigmoid, dsigmoid
from Functions.errorFunctions import MSE
from Classes.Layer import Layer
from Classes.LayerGen import LayerGenerator
from random import random
from Classes.Perceptron import Perceptron
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
np.random.seed(1)


In [23]:
data = pd.read_csv('../Data/DataLaba1/energy_task_moded_removed_nan.csv')
sl = data.shape[0]
scale = MinMaxScaler().fit_transform(data)
X_train, X_test, y_train, y_test = train_test_split(scale.T[:, :-2], scale.T[:, -1], test_size=0.25)



In [24]:
scale[:, :-2].shape, scale[:, -1].shape


((18538, 28), (18538,))

In [25]:
max(y_train), min(y_train)


(1.0, 0.0)

In [26]:
layer_mass = LayerGenerator(sizes_of_input_layer=X_train.shape[1],
                            sizes_of_hidden_layers=[X_train.shape[1] // 2, X_train.shape[1] // 4],
                            sizes_of_output_layer=1,
                            summators=[lambda w, x, d: w.dot(x.T) + d, 
                                       lambda w, x, d: w.dot(x.T) + d,
                                       lambda w, x, d: w.dot(x.T) + d,
                                       lambda w, x, d: w.dot(x.T) + d],
                            dsummators=[lambda w, x, d: (x, d),
                                        lambda w, x, d: (x, d),
                                        lambda w, x, d: (x, d),
                                        lambda w, x, d: (x, d)],
                            activation_functions=[sigmoid,
                                                  sigmoid,
                                                  sigmoid,
                                                  sigmoid],
                            dactivation_functions=[dsigmoid,
                                                   dsigmoid,
                                                   dsigmoid,
                                                   dsigmoid],
                            function_of_generation=lambda a, b: np.random.rand(a, b)).generate()
layer_mass


In [27]:
X_train.shape


(22, 18536)

In [28]:
def batch_spliter(x, y, size, num):
    batches = list()
    for _ in range(num):
        js = np.random.shuffle(np.arange(size))
        batches.append((x[js][0], y[js][0]))
    return batches


# Not trained

In [29]:
k = []
for i in layer_mass:
    k.append(np.array(i.get_weights(), copy=True))
    print(i.get_weights())


[[0.91396202 0.45720481 0.43069857 ... 0.11574774 0.91328866 0.88396382]
 [0.31012219 0.0921288  0.86035901 ... 0.47779916 0.61342873 0.2591459 ]
 [0.40172844 0.27336398 0.05076561 ... 0.28517195 0.39874098 0.90691154]
 ...
 [0.23096955 0.49857544 0.15016932 ... 0.75975348 0.28699937 0.73471961]
 [0.0331401  0.9083018  0.58257696 ... 0.40158846 0.26487134 0.70652817]
 [0.80017891 0.40359934 0.68061741 ... 0.31103597 0.49551722 0.585855  ]]
[[0.8898169  0.64986933 0.13244185 ... 0.47790409 0.99161274 0.91882621]
 [0.72423841 0.84039229 0.56960939 ... 0.98822525 0.91595708 0.00177404]
 [0.37145467 0.7675109  0.41997672 ... 0.82292086 0.21793237 0.90423363]
 ...
 [0.64351596 0.25486628 0.7067317  ... 0.08868618 0.52367673 0.57470745]
 [0.59855439 0.63626215 0.65652005 ... 0.9385239  0.12484929 0.53234928]
 [0.17012315 0.92651222 0.25553959 ... 0.32343476 0.90132421 0.45324889]]
[[0.20449402 0.09285827 0.62045068 ... 0.52198211 0.19490728 0.94646861]]


In [30]:
a = Perceptron(layer_mass)
res = [a.predict(i)[0] for i in X_train[:200]]
print(MSE(res, y_train[:200]))
for p, y in zip(res, y_train[:200]):
    print(f'p:{p},\t y:{y},\t d:{abs(p-y)}')


5.520138809073515
p:[1.],	 y:0.4,	 d:[0.6]
p:[1.],	 y:0.4342105263157895,	 d:[0.56578947]
p:[1.],	 y:0.2857142857142857,	 d:[0.71428571]
p:[1.],	 y:0.6661705142558345,	 d:[0.33382949]
p:[1.],	 y:0.9197465681098203,	 d:[0.08025343]
p:[1.],	 y:0.8956916099773242,	 d:[0.10430839]
p:[1.],	 y:0.7995458067464272,	 d:[0.20045419]
p:[1.],	 y:0.8647242455775233,	 d:[0.13527575]
p:[1.],	 y:0.0,	 d:[1.]
p:[1.],	 y:0.5790621593952523,	 d:[0.42093784]
p:[1.],	 y:1.0,	 d:[0.]
p:[1.],	 y:0.14285714285714285,	 d:[0.85714286]
p:[1.],	 y:0.7705142623922883,	 d:[0.22948574]
p:[1.],	 y:0.39622641509433965,	 d:[0.60377358]
p:[1.],	 y:0.7395035460992909,	 d:[0.26049645]
p:[1.],	 y:0.7552447552447552,	 d:[0.24475524]
p:[1.],	 y:0.0,	 d:[1.]
p:[1.],	 y:0.7811922035851471,	 d:[0.2188078]
p:[1.],	 y:0.8648648648648651,	 d:[0.13513514]
p:[1.],	 y:0.7885800224130404,	 d:[0.21141998]
p:[1.],	 y:0.336582798700051,	 d:[0.6634172]
p:[1.],	 y:0.6329017312526195,	 d:[0.36709827]


In [31]:
np.array(res).mean(), np.array(res).std(), np.array(res).min()


(1.0, 0.0, 1.0)

In [32]:
# -1.1027074438226645
r2_score(np.array(res) >= np.array(res).mean(), y_train[:200])


0.0

# Trained

In [33]:
teacher = PerceptronTeacher(layers=layer_mass,
                                 step=1e-1,
                                 batch_spliter=lambda a, b: batch_spliter(a, b, a.shape[0]//2, 1),
                                 epochs=2,
                                 error_function=MSE,
                                 derror_function=lambda x, y: 2 * x - 2 * y)


In [34]:
tl = teacher.teach(X_train[:200], y_train[:200])


shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)
shapes	a: (1, 9268), s: (1, 1)
shapes	a: (1, 9268), s: (9268, 1)
shapes	a: (1, 18536), s: (9268, 1)


KeyboardInterrupt: 

In [ ]:
for i in tl:
    print(i.get_weights())


[[0.91396202 0.45720481 0.43069857 ... 0.11574774 0.91328866 0.88396382]
 [0.31012219 0.0921288  0.86035901 ... 0.47779916 0.61342873 0.2591459 ]
 [0.40172844 0.27336398 0.05076561 ... 0.28517195 0.39874098 0.90691154]
 ...
 [0.23096955 0.49857544 0.15016932 ... 0.75975348 0.28699937 0.73471961]
 [0.0331401  0.9083018  0.58257696 ... 0.40158846 0.26487134 0.70652817]
 [0.80017891 0.40359934 0.68061741 ... 0.31103597 0.49551722 0.585855  ]]
[[0.8898169  0.64986933 0.13244185 ... 0.47790409 0.99161274 0.91882621]
 [0.72423841 0.84039229 0.56960939 ... 0.98822525 0.91595708 0.00177404]
 [0.37145467 0.7675109  0.41997672 ... 0.82292086 0.21793237 0.90423363]
 ...
 [0.64351596 0.25486628 0.7067317  ... 0.08868618 0.52367673 0.57470745]
 [0.59855439 0.63626215 0.65652005 ... 0.9385239  0.12484929 0.53234928]
 [0.17012315 0.92651222 0.25553959 ... 0.32343476 0.90132421 0.45324889]]
[[0.20449402 0.09285827 0.62045068 ... 0.52198211 0.19490728 0.94646861]]


In [ ]:
for i in tl:
    print(i.get_weights())

[[0.91396202 0.45720481 0.43069857 ... 0.11574774 0.91328866 0.88396382]
 [0.31012219 0.0921288  0.86035901 ... 0.47779916 0.61342873 0.2591459 ]
 [0.40172844 0.27336398 0.05076561 ... 0.28517195 0.39874098 0.90691154]
 ...
 [0.23096955 0.49857544 0.15016932 ... 0.75975348 0.28699937 0.73471961]
 [0.0331401  0.9083018  0.58257696 ... 0.40158846 0.26487134 0.70652817]
 [0.80017891 0.40359934 0.68061741 ... 0.31103597 0.49551722 0.585855  ]]
[[0.8898169  0.64986933 0.13244185 ... 0.47790409 0.99161274 0.91882621]
 [0.72423841 0.84039229 0.56960939 ... 0.98822525 0.91595708 0.00177404]
 [0.37145467 0.7675109  0.41997672 ... 0.82292086 0.21793237 0.90423363]
 ...
 [0.64351596 0.25486628 0.7067317  ... 0.08868618 0.52367673 0.57470745]
 [0.59855439 0.63626215 0.65652005 ... 0.9385239  0.12484929 0.53234928]
 [0.17012315 0.92651222 0.25553959 ... 0.32343476 0.90132421 0.45324889]]
[[0.20449402 0.09285827 0.62045068 ... 0.52198211 0.19490728 0.94646861]]


In [ ]:
for i, j in zip(k, tl):
    print(i - j.get_weights())


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
a = Perceptron(tl)
res = [a.predict(i)[0] for i in X_train[:200]]
print(MSE(res, y_train[:200]))
for p, y in zip(res, y_train[:200]):
    print(f'p:{p},\t y:{y},\t d:{abs(p-y)}')


5.520138809073515
p:[1.],	 y:0.4,	 d:[0.6]
p:[1.],	 y:0.4342105263157895,	 d:[0.56578947]
p:[1.],	 y:0.2857142857142857,	 d:[0.71428571]
p:[1.],	 y:0.6661705142558345,	 d:[0.33382949]
p:[1.],	 y:0.9197465681098203,	 d:[0.08025343]
p:[1.],	 y:0.8956916099773242,	 d:[0.10430839]
p:[1.],	 y:0.7995458067464272,	 d:[0.20045419]
p:[1.],	 y:0.8647242455775233,	 d:[0.13527575]
p:[1.],	 y:0.0,	 d:[1.]
p:[1.],	 y:0.5790621593952523,	 d:[0.42093784]
p:[1.],	 y:1.0,	 d:[0.]
p:[1.],	 y:0.14285714285714285,	 d:[0.85714286]
p:[1.],	 y:0.7705142623922883,	 d:[0.22948574]
p:[1.],	 y:0.39622641509433965,	 d:[0.60377358]
p:[1.],	 y:0.7395035460992909,	 d:[0.26049645]
p:[1.],	 y:0.7552447552447552,	 d:[0.24475524]
p:[1.],	 y:0.0,	 d:[1.]
p:[1.],	 y:0.7811922035851471,	 d:[0.2188078]
p:[1.],	 y:0.8648648648648651,	 d:[0.13513514]
p:[1.],	 y:0.7885800224130404,	 d:[0.21141998]
p:[1.],	 y:0.336582798700051,	 d:[0.6634172]
p:[1.],	 y:0.6329017312526195,	 d:[0.36709827]


In [ ]:
np.array(res).mean(), np.array(res).std(), np.array(res).min()


(0.8039168190946774, 0.0023756631773083764, 0.7998516383000169)

In [ ]:
# -1.1027074438226645
r2_score(np.array(res) >= 0.6, y_train.to_numpy()[:200])


0.36371100164203607