# Импорт.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from Classes.CartTreeClassifier import CartTreeClassifier
from Classes.CartTreeTeacher import CartTreeTeacher

from Functions.metrics import *
from Functions.split_functions import *
from Functions.spreading_functions import *
from Functions.search_split_functions import *

from Functions.metrics import accuracy
from sys import setrecursionlimit

In [2]:
setrecursionlimit(5000)

# Загрузка Dataset'а.

In [3]:
models = pd.read_csv('../Data/DataLaba2/neo_task_smoted.csv')
X_train, X_test, y_train, y_test = train_test_split(models.drop('hazardous', axis=1), models['hazardous'], test_size=0.8, random_state=42)

In [4]:
y_test

30724     0.0
35732     0.0
118948    1.0
76136     0.0
36621     0.0
         ... 
78301     1.0
156971    1.0
21441     0.0
98558     1.0
77859     0.0
Name: hazardous, Length: 131194, dtype: float64

In [5]:
X_train

est_diameter_max  relative_velocity  miss_distance  absolute_magnitude
141239         -0.981476          -0.675772       0.590152           -0.151944
63113          -0.986259          -0.574666       0.795103           -0.098039
29924          -0.994915          -0.449857      -0.118752            0.081352
109159         -0.986257          -0.716450      -0.881387           -0.098033
64320          -0.992601          -0.507073      -0.517601            0.013767
...                  ...                ...            ...                 ...
119879         -0.981295          -0.635733      -0.532257           -0.153718
103694         -0.984032          -0.714345       0.317797           -0.125175
131932         -0.992591          -0.636823      -0.081927            0.013857
146867         -0.989026          -0.652895      -0.262361           -0.057075
121958         -0.981846          -0.532647      -0.703201           -0.148371

[32798 rows x 4 columns]

In [6]:
y_test.shape, y_train.shape, X_train.shape

((131194,), (32798,), (32798, 4))

In [7]:
g, p, n = search_params_that_equiv_to_majority_class(X_train.to_numpy()[0:50], y_train.to_numpy()[0:50])

In [8]:
g, p, n

(0.275, 0.079682937004589, 3)

In [9]:
y_train.to_numpy()[0:50][X_train.to_numpy()[0:50].T[n]>p].shape[0]

17

In [10]:
y_train.to_numpy()[0:50][X_train.to_numpy()[0:50].T[n]<=p].shape[0]

33

In [11]:
ctc = CartTreeClassifier()
ctt = CartTreeTeacher(ctc, lambda a, b: classic_split(a, b[1], b[2]), search_params_that_equiv_to_majority_class, 5)
ctt.teach(X_train.to_numpy()[0:10], y_train.to_numpy()[0:10])

In [12]:
ctc.predict(X_train.to_numpy()[0:100]), y_train.to_numpy()[0:100]

(array([1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
        1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1.]),
 array([1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1.,
        1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.]))

In [13]:
ctc.predict(X_test.to_numpy()[0:1])

array([1.])

In [14]:
z = ctc.predict(X_test.to_numpy()[0:1000])

In [15]:
accuracy(z, y_test[0:1000])

0.596