In [1]:
import numpy as np
import pandas as pd
from Classes.PercepTeacher import PerceptronTeacher
from Functions.function_of_activation import sigmoid, dsigmoid
from Functions.errorFunctions import MSE
from Classes.Layer import Layer
from Classes.LayerGen import LayerGenerator
from random import random
from Classes.Perceptron import Perceptron
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from Classes.LossFunction import LossFunction
from sklearn.metrics import classification_report
from Functions.errorFunctions import R2
from Classes.perec import WeightsSearch
np.random.seed(1)


In [2]:
data = pd.read_csv('../Data/DataLaba1/energy_task_moded_removed_nan.csv')
sl = data.shape[0]
scale = MinMaxScaler().fit_transform(data)
X_train, X_test, y_train, y_test = train_test_split(
    scale[:, :-2], scale[:, -1], test_size=0.25)


In [3]:
layers_dims = [28, 64, 128, 64, 32, 16, 1]

In [4]:
neuron = WeightsSearch(layers_dims,  learning_rate=0.00001, num_iterations = 1000)

In [5]:
train = neuron.search(X_train, y_train)


In [6]:
pred_test = neuron.predict_regr(X_test, train[0])


In [7]:
layers = []
for i in range(0, len(train[0]), 2):
    w = train[0][list(train[0].keys())[i]]
    d = train[0][list(train[0].keys())[i+1]]
    print(w.shape, d.shape)
    layers.append(Layer(w, d, sigmoid, dsigmoid))


(64, 28) (64, 1)
(128, 64) (128, 1)
(64, 128) (64, 1)
(32, 64) (32, 1)
(16, 32) (16, 1)
(1, 16) (1, 1)


In [8]:
a = Perceptron(layers)
res = np.array([a.predict(i)[0] for i in X_train[:200]])
# print(MSE((res), y_train[:200]))
for p, y in zip(res, y_train[:200]):
    print(f'p:{p},\t y:{y},\t d:{abs(p-y)}')


p:0.03109543704945056,	 y:0.46853146853146854,	 d:0.437436031482018
p:0.03109543704945018,	 y:0.8391608391608392,	 d:0.808065402111389
p:0.031095437049443963,	 y:0.6363636363636364,	 d:0.6052681993141924
p:0.03109543704945535,	 y:0.38461538461538464,	 d:0.3535199475659293
p:0.03109543704944973,	 y:1.0,	 d:0.9689045629505503
p:0.031095437049455527,	 y:0.2097902097902098,	 d:0.17869477274075427
p:0.031095437049446725,	 y:0.0979020979020979,	 d:0.06680666085265118
p:0.031095437049451734,	 y:0.38461538461538464,	 d:0.3535199475659329
p:0.031095437049452758,	 y:0.6993006993006993,	 d:0.6682052622512465
p:0.031095437049452675,	 y:0.8671328671328671,	 d:0.8360374300834144
p:0.031095437049448133,	 y:0.8531468531468531,	 d:0.822051416097405
p:0.031095437049451096,	 y:0.055944055944055944,	 d:0.024848618894604848
p:0.03109543704945362,	 y:0.7482517482517482,	 d:0.7171563112022946
p:0.03109543704944502,	 y:0.16783216783216784,	 d:0.1367367307827228
p:0.031095437049449785,	 y:0.6643356643356644,	 

In [12]:
res

array([0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109544,
       0.03109544, 0.03109544, 0.03109544, 0.03109544, 0.03109

In [9]:
pred_test[0]


array([-0.01693982, -0.00828025, -0.00740616, ..., -0.00672988,
        0.0002389 , -0.01265975])

In [10]:
y_train

array([0.46853147, 0.83916084, 0.63636364, ..., 0.20979021, 0.03496503,
       0.48251748])

In [11]:
R2(y_train, pred_test[0]*(-2)+0.5)


0.9979402398914003