In [35]:
import numpy as np
import pandas as pd
from Classes.PercepTeacher import PerceptronTeacher
from Functions.function_of_activation import sigmoid, dsigmoid
from Functions.errorFunctions import MSE
from Classes.Layer import Layer
from Classes.LayerGen import LayerGenerator
from random import random
from Classes.Perceptron import Perceptron
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from Classes.perec import NeuralWeb
from Classes.LossFunction import LossFunction
from sklearn.metrics import classification_report, accuracy_score
from Functions.errorFunctions import R2
np.random.seed(1)


In [36]:
data = pd.read_csv('../Data/DataLaba2/neo_task_moded_norm.csv')
sl = data.shape[0]
scale = MinMaxScaler().fit_transform(data)
X_train, X_test, y_train, y_test = train_test_split(
    scale[:, :-2], scale[:, -1], test_size=0.25)


In [37]:
layers_dims = [3, 64, 128, 64, 32, 16, 1]

In [48]:
neuron = NeuralWeb(layers_dims,  learning_rate=0.001, num_iterations = 100)

In [49]:
train = neuron.iterations(X_train, y_train)


Param {'W1': array([[ 0.93781623, -0.35319773, -0.3049401 ],
       [-0.61947872,  0.49964333, -1.32879399],
       [ 1.00736754, -0.43948301,  0.18419731],
       [-0.14397405,  0.84414841, -1.18942279],
       [-0.18614766, -0.22173389,  0.65458209],
       [-0.63502252, -0.09955147, -0.50683179],
       [ 0.02437212,  0.33648852, -0.63544278],
       [ 0.66090654,  0.52053365,  0.29011524],
       [ 0.52010942, -0.39475046, -0.0709507 ],
       [-0.54026673, -0.15466525,  0.30620087],
       [-0.39933052, -0.22906576, -0.39673934],
       [-0.4879797 , -0.38754413, -0.00731191],
       [-0.64507943,  0.13533997,  0.95828723],
       [ 0.4284194 , -0.11075631, -0.51247282],
       [-0.43137204,  0.97713912,  0.02933387],
       [-0.36776961,  0.11022511,  1.21258287],
       [ 0.0693738 ,  0.35634238,  0.17330342],
       [-0.20337154, -0.65963319, -0.20169311],
       [-0.12060514,  0.33868706,  0.4843873 ],
       [ 0.53757204,  0.16488392,  0.51103649],
       [-0.43555185,  0.723

In [50]:
pred_test = neuron.predict_regr(X_test, train[0])


Z [[-0.12710209 -0.12127562 -0.18786753 ... -0.27207418 -0.12274226
  -0.32291883]
 [-0.28638288 -0.11878668 -0.34279409 ... -0.90877163 -0.35534565
  -0.85120842]
 [-0.05399923 -0.10081272 -0.08662806 ...  0.01882468 -0.02909842
  -0.0410093 ]
 ...
 [-0.10132349 -0.06865016 -0.13611791 ... -0.26765775 -0.11120153
  -0.28073198]
 [-0.03298937 -0.0339078  -0.01046393 ...  0.02402691 -0.03397752
   0.03952395]
 [ 0.03317646  0.06714665  0.11465174 ...  0.11828243  0.0112975
   0.20373364]]
A
 [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.01882468 0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.02402691 0.         0.03952395]
 [0.03317646 0.06714665 0.11465174 ... 0.11828243 0.0112975  0.20373364]]
Z [[-0.09738355 -0.10664231 -0.19745911 ... -0.17649827 -0.0

In [51]:
pred_test[0] > pred_test[0].mean()


array([False, False, False, ..., False, False, False])

In [52]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [53]:
print(classification_report(pred_test[0] > pred_test[0].mean(), y_train))
print(accuracy_score(pred_test[0] > pred_test[0].mean(), y_train))


              precision    recall  f1-score   support

       False       0.99      0.90      0.95     67571
        True       0.02      0.25      0.04       556

    accuracy                           0.90     68127
   macro avg       0.51      0.58      0.49     68127
weighted avg       0.99      0.90      0.94     68127

0.8988213190071485
